FROM node:lts-alpine
ENV NODE_ENV=production
ENV VUE_APP_BASE_URL_DEBUG=http://0.0.0.0:3000
ENV VUE_APP_BASE_URL_PROD=http://0.0.0.0:3000
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 8081
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "dev"]
